services:
  # PHP-FPM Service
  php:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rent_cars_php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./var:/var/www/html/var
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=16&charset=utf8
      APP_ENV: ${APP_ENV:-dev}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - rent_cars_network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: rent_cars_nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - rent_cars_network

  # PostgreSQL Database Service
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: rent_cars_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - rent_cars_network

volumes:
  database_data:

networks:
  rent_cars_network:
    driver: bridge
